### ISSUE TITLE
conversion on int

### ISSUE THREAD

**Issue by yamadasuzaku** [hidet/xys#1]
バージョン問題だと思いますが、、
material.pyの79行目のxrl.AtomicNumberToSymbolに渡しているzをint型
xys_gui.pyの569行目と571行目のlineをint型
に変更すると動きました。

**Comment by hidet** [comment]
ありがとうございます。簡単にですが int を渡すようにしてみました。私の環境だと int で渡っているので、バージョンの違いにより今後また同じような箇所が出てくるかもしれません。

**Comment by yamadasuzaku** [comment]
ありがとうございます！
